### ISSUE TITLE
副标题

### ISSUE THREAD

**Issue by colinaaa** [colinaaa/algorithm-course-notes#11]
求一位同学贡献一个副标题

![image](https://user-images.githubusercontent.com/40660121/98897605-c3bdb580-24e6-11eb-98d4-b1fc9e994564.png)

**Comment by NickLee2050** [comment]
Always be patient, sharp and diligent.

**Comment by colinaaa** [comment]
Added in 6ef3281, closed.

Reopen this issue if you perfer other subtitles.
