### ISSUE TITLE
slight error to be corrected

### ISSUE THREAD

**Issue by NickLee2050** [colinaaa/algorithm-course-notes#16]
https://github.com/colinaaa/algorithm-course-notes/blob/99741ef3dc05f37c6d6f56e1fd62b0a8513d2c7c/src/Ln11-LargeIntegerMultiplication.tex#L76
In line 76, the (C2 + C1) \ll (n - 1) should be corrected as:
(C2 + C1) \ll (n / 2) 

https://github.com/colinaaa/algorithm-course-notes/blob/99741ef3dc05f37c6d6f56e1fd62b0a8513d2c7c/src/Ln11-LargeIntegerMultiplication.tex#L141
Also in line 141, the (C_0 - C_2 - C_1) \ll (n - 1) should be corrected as:
(C_0 - C_2 - C_1) \ll (n / 2)

**Comment by colinaaa** [comment]
考完组原我改一下吧（
