### ISSUE TITLE
排版错误

### ISSUE THREAD

**Issue by Gousheng-dd** [colinaaa/algorithm-course-notes#26]
https://github.com/colinaaa/algorithm-course-notes/blob/29f6e0cab62d3d68c2c4fccb574674ebff7826ac/src/Image-segmentation.tex#L4
本行使用\centering，使得之后章节正文全部居中显示了，建议删除。

**Comment by colinaaa** [comment]
拿大括号括起来就行了，我待会改一下吧

**Comment by colinaaa** [comment]
@Gousheng-dd check it out #28
