### ISSUE TITLE
图片过大 & example定理

### ISSUE THREAD

**Issue by colinaaa** [colinaaa/algorithm-course-notes#43]
example中的定理cp过来没删掉

https://github.com/colinaaa/algorithm-course-notes/blob/dc249cf1dd3433772d3af4358d8ca4085fec3d35/src/Proof-of-Statute.tex#L12-L14

图片太大了，scale一下（下面一个图也是）

https://github.com/colinaaa/algorithm-course-notes/blob/dc249cf1dd3433772d3af4358d8ca4085fec3d35/src/Proof-of-Statute.tex#L53

![image](https://user-images.githubusercontent.com/40660121/102753260-dfe62980-43a5-11eb-9587-fcacb2f9e43e.png)

辛苦 @qzylalala 改一下吧，当时没认真review（

**Comment by qzylalala** [comment]
okk，我的问题
